site_name: D&D Campaign Library
theme:
  name: material
nav:
  - Home: index.md
  - Game Logs:
      - "Session 1": Game_logs/session_1.md
      - "Session 2": Game_logs/session_2.md
  - Locations:
      - "Tribor Trail": Locations/Tribor_Trail_History.md
      - "Neverwinter": Locations/City_of_Neverwinter.md
  - NPCs:
      - "Asher Strongfoot": NPCs/Asher_Strongfoot.md
  - Rules & House Rules: Rules/house_rules.md
