site_name: D&D Campaign Library
theme:
  name: material
  palette:
    scheme: slate  # ✅ Correct
    primary: deep purple
    accent: amber

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - toc.integrate

nav:
  - Home: index.md
  - Game Logs: 
      - "Session 1": Game_logs/session_1.md
  - Locations:
      - "Tribor Trail": Locations/Tribor_Trail_History.md
  - NPCs:
      - "Asher Strongfoot": NPCs/Asher_Strongfoot.md
  - Rules & House Rules: Rules/house_rules.md

site_url: https://robinv87.github.io/DnD-Campaigns/
